protected/models/Group.php
<?php

/**
 * This is the model class for table "tbl_group".
 *
 * The followings are the available columns in table 'tbl_group':
 * @property integer $id
 * @property string $name
 * @property integer $status
 * @property string $description
 * @property string $note
 * @property string $create_date
 * @property integer $create_id
 * @property string $update_date
 * @property integer $update_id
 * @property User[] $users
 * @property integer $usersCount

 *
 * The followings are the available model relations:
 * @property UserGroupAssignment[] $userGroupAssignments
 */
class Group extends ProjStarActiveRecord
{

    const STATUS_IDEL = 0;
    const STATUS_ACTIVE = 1;

	/**
	 * @return string the associated database table name
	 */
	public function tableName()
	{
		return 'tbl_group';
	}

	/**
	 * @return array validation rules for model attributes.
	 */
	public function rules()
	{
		// NOTE: you should only define rules for those attributes that
		// will receive user inputs.
		return array(
			array('name,create_id, create_date', 'required'),
			array('status, create_id, update_id', 'numerical', 'integerOnly'=>true),
			array('name', 'length', 'max'=>255),
			array('description, note', 'safe'),

			array('id, name, status, description, note, create_date, create_id, update_date, update_id', 'safe', 'on'=>'search'),
		);
	}

	/**
	 * @return array relational rules.
	 */
	public function relations()
	{
		// NOTE: you may need to adjust the relation name and the related
		// class name for the relations automatically generated below.
		return array(
			'userGroupAssignments' => array(self::HAS_MANY, 'UserGroupAssignment', 'group_id'),
            'users'=>array(self::MANY_MANY,'User','tbl_user_group_assignment(group_id,user_id)'),
            'usersCount'=>array(self::STAT,'User','tbl_user_group_assignment(group_id,user_id)'),
		);
	}

	/**
	 * @return array customized attribute labels (name=>label)
	 */
	public function attributeLabels()
	{
		return array(
			'id' => 'ID',
			'name' => 'Group Name',
			'status' => 'Group Status',
			'description' => 'Group Description',
			'note' => 'Notes',
			'create_date' => 'Create Date',
			'create_id' => 'Create',
			'update_date' => 'Update Date',
			'update_id' => 'Update',
		);
	}

	/**
	 * Retrieves a list of models based on the current search/filter conditions.
	 *
	 * Typical usecase:
	 * - Initialize the model fields with values from filter form.
	 * - Execute this method to get CActiveDataProvider instance which will filter
	 * models according to data in model fields.
	 * - Pass data provider to CGridView, CListView or any similar widget.
	 *
	 * @return CActiveDataProvider the data provider that can return the models
	 * based on the search/filter conditions.
	 */
	public function search()
	{
		// @todo Please modify the following code to remove attributes that should not be searched.

		$criteria=new CDbCriteria;

		$criteria->compare('id',$this->id);
		$criteria->compare('name',$this->name,true);
		$criteria->compare('status',$this->status);
		$criteria->compare('description',$this->description,true);
		$criteria->compare('note',$this->note,true);
		$criteria->compare('create_date',$this->create_date,true);
		$criteria->compare('create_id',$this->create_id);
		$criteria->compare('update_date',$this->update_date,true);
		$criteria->compare('update_id',$this->update_id);

		return new CActiveDataProvider($this, array(
			'criteria'=>$criteria,
		));
	}

    public function addMember($userId){
        try{
            Yii::app()->db->createCommand()->insert('tbl_user_group_assignment',array(
                'user_id'=>$userId,
                'group_id'=>$this->id,
            ));
        }catch(CDbException $e){

        }

    }

    public function deleteMember($userId){
        try{
            Yii::app()->db->createCommand()->delete('tbl_user_group_assignment',"user_id=:user_id AND group_id=:group_id",array(
                ':user_id'=>$userId,
                ':group_id'=>$this->id,
            ));
        }catch(CDbException $e){

        }
    }
	/**
	 * Returns the static model of the specified AR class.
	 * Please note that you should have this exact method in all your CActiveRecord descendants!
	 * @param string $className active record class name.
	 * @return Group the static model class
	 */
	public static function model($className=__CLASS__)
	{
		return parent::model($className);
	}
}

protected/controllers/GroupController.php
<?php

class GroupController extends Controller
{
    /**
     * @var string the default layout for the views. Defaults to '//layouts/column2', meaning
     * using two-column layout. See 'protected/views/layouts/column2.php'.
     */
    public $layout = '//layouts/column2';

    /**
     * @return array action filters
     */
    public function filters()
    {
        return array(
            'checkAccess',
            'adminAccess',
        );
    }

    /**
     * Specifies the access control rules.
     * This method is used by the 'accessControl' filter.
     * @return array access control rules
     */
    public function accessRules()
    {
        return array(
            array('allow', // allow all users to perform 'index' and 'view' actions
                'actions' => array('index', 'view'),
                'users' => array('*'),
            ),
            array('allow', // allow authenticated user to perform 'create' and 'update' actions
                'actions' => array('create', 'update'),
                'users' => array('@'),
            ),
            array('allow', // allow admin user to perform 'admin' and 'delete' actions
                'actions' => array('admin', 'delete'),
                'users' => array('admin'),
            ),
            array('deny', // deny all users
                'users' => array('*'),
            ),
        );
    }

    /**
     * Displays a particular model.
     * @param integer $id the ID of the model to be displayed
     */
    public function actionView($id)
    {
        $this->render('view', array(
            'model' => $this->loadModel($id),
        ));
    }

    /**
     *
     * This method does the following:
     * 1- creates a new Group model and store it in the database.
     * 2- Add the "creation of Task entry" to the Task Log
     * @return string
     * @dataType json
     *
     */
    public function actionCreate()
    {
        if (Yii::app()->request->isAjaxRequest) {
            $model = new Group;
            if (isset($_POST['Group'])) {
                $model->attributes = $_POST['Group'];
                $model->create_id = Yii::app()->user->id;
                $model->create_date = date('Y-m-d H:i:s');
                $model->status = Group::STATUS_ACTIVE;
                if ($model->save()){
                    echo CJSON::encode(array(
                        'status'=>true,
                        'message'=>'A new Group was created',
                    ));
                }else{
                    echo CJSON::encode(array(
                        'status'=>false,
                        'message'=> 'Could\'t create a new Group',
                    ));
                }
            }
        } else {
            throw new CHttpException(400);
        }
    }


    /**
     *
     *  This method is called Via Ajax GET request.
     *  It return an update group info form for a particular Group.
     *  @param integer $id the id of the Group to be modified
     *  @return string
     *  @dataType html
     *
     */

    public function actionGetUpdateForm($id){
        if(Yii::app()->request->isAjaxRequest){
            $groupModel = $this->loadModel(intval($id));
            echo $this->renderPartial('_form',array(
                'groupModel'=>$groupModel,
            ),false,true);
        }else{
            throw new CHttpException(400);
        }
    }


    /**
     *
     *  This method is called Via Ajax POST request.
     *  @param integer $_POST['Group']['id'] the id of the Group model we want to modify
     *  @return string
     *  @dataType json
     *
     */
    public function actionUpdate()
    {
        if(Yii::app()->request->isAjaxRequest){
            $model = $this->loadModel($_POST['Group']['id']);
            $model->attributes = $_POST['Group'];
            if($model->save()){
                echo CJSON::encode(array(
                    'status'=>true,
                    'message'=>'The Group\'s info has been updated'
                ));
            }else{
                echo CJSON::encode(array(
                    'status'=>false,
                    'message'=>'Error'
                ));
            }
        }else{
            throw new CHttpException(400);
        }

    }

    /**
     *
     * Deletes a particular Group model.
     * The method also deletes the association between the group and its members
     * @param integer $_POST['id'] the ID of the model to be deleted
     *
     */
    public function actionDelete()
    {
        if(Yii::app()->request->isAjaxRequest){
            if(isset($_POST['id'])){
                $groupId = intval($_POST['id']);
                $group = Group::model()->findByPk($groupId);
                $deleteCount = Yii::app()->db->createCommand()->delete('tbl_user_group_assignment','group_id=:group_id',array(
                    ':group_id'=>$group->id,
                ));
                if($group->delete()){
                    echo CJSON::encode(array(
                        'status'=>true,
                        'message'=>'The Group "'.$group->name.'" was deleted successfully.'
                    ));
                }else{
                    echo CJSON::encode(array(
                        'status'=>false,
                        'message'=>'The Group "'.$group->name.'" couldn\'t be deleted.',
                    ));
                }
            }
        }else{
            throw new CHttpException(400);
        }
    }

    public function actionGetCreateForm()
    {
        if (Yii::app()->request->isAjaxRequest) {
            $groupModel = new Group;
            echo $this->renderPartial('_form', array(
                'groupModel' => $groupModel,
            ), false, true);
        }
    }


    /**
     * Lists all models.
     */
    public function actionIndex()
    {
        $groupModel = new Group('search');
        $groupModel->unsetAttributes();

        if (isset($_GET['Group'])) {
            $groupModel->attributes = $_GET['Group'];
        }

        $this->render('index', array(
            'groupModel' => $groupModel,
        ));
    }

    public function actionUpdateUsers($id){
        if(Yii::app()->request->isAjaxRequest){
            $model = $this->loadModel(intval($id));
            if(isset($_POST['user_id'])){
                foreach($_POST['user_id'] as $userId){
                    $model->addMember($userId);
                }
            }
        }else{
            throw new CHttpException(400);
        }
    }

    public function actionUsers($id){
        $group = Group::model()->findByPk(intval($id));
        $users = User::model()->findAll();
        foreach($users as $user){
            $user->groupId = $group->id;
        }
        $userDataProvider = new CActiveDataProvider('User');
        $userDataProvider->setData($users);
        $this->render("users",array(
            'groupModel'=>$group,
            'userDataProvider'=>$userDataProvider
        ));
    }

    public function actionDeleteFromGroup($userId,$groupId){
        if(Yii::app()->request->isAjaxRequest){
            $user = User::model()->findByPk($userId);
            $group = Group::model()->findByPk($groupId);

            $group->deleteMember($user->id);
            echo CJSON::encode(array(
                'status'=>true,
                'message'=>'The User Was Deleted!',
            ));

        }
    }
    /**
     * Manages all models.
     */
    public function actionAdmin()
    {
        $model = new Group('search');
        $model->unsetAttributes(); // clear any default values
        if (isset($_GET['Group']))
            $model->attributes = $_GET['Group'];

        $this->render('admin', array(
            'model' => $model,
        ));
    }

    public function actionGetGroupMembers($id){
        $groupId = intval($id);
        $group = Group::model()->findByPk($groupId);
        $members = $group->users;
        echo $this->renderPartial('partials/members-list',array(
            'members'=>$members,
        ),false,true);
    }

    /**
     * Returns the data model based on the primary key given in the GET variable.
     * If the data model is not found, an HTTP exception will be raised.
     * @param integer $id the ID of the model to be loaded
     * @return Group the loaded model
     * @throws CHttpException
     */
    public function loadModel($id)
    {
        $model = Group::model()->findByPk($id);
        if ($model === null)
            throw new CHttpException(404, 'The requested page does not exist.');
        return $model;
    }

    /**
     * Performs the AJAX validation.
     * @param Group $model the model to be validated
     */
    protected function performAjaxValidation($model)
    {
        if (isset($_POST['ajax']) && $_POST['ajax'] === 'group-form') {
            echo CActiveForm::validate($model);
            Yii::app()->end();
        }
    }
    public function filterCheckAccess($chain){
        if(!Yii::app()->user->isGuest){
            $chain->run();
        }else{
            Yii::app()->request->redirect(array('site/login'));
        }
    }
    public function filterAdminAccess($chain){
        if(Yii::app()->user->checkAccess('administrator')){
            $chain->run();
        }else{
            throw new CHttpException(403);
        }
    }
}

protected/views/group/partials/_group-details.php
<div class="details-panel panel panel-success">
    <div class="panel-heading">
        <span class="header-caption">Group Details</span>
    </div>
    <div class="panel-body">
        <div id="group-prompt">
            <div class="select-prompt">Select a Group show its members</div>
        </div>
        <div id="group-details" style="display: none;">
        </div>
    </div>
</div>

protected/views/group/partials/group-list.php
<?php $this->widget('zii.widgets.grid.CGridView', array(
    'id' => 'group-grid',
    'showTableOnEmpty' => false,

    'rowHtmlOptionsExpression' => 'array("class"=>"group-grid-row","group-id"=>$data->id,"group-name"=>$data->name,"group-description"=>$data->description,"group-note"=>$data->note,"group-status"=>$data->status)',
    'summaryText' => '<span>Total No Of Groups: {count}</span><br/>',
    'emptyText' => 'No Groups Available',
    'afterAjaxUpdate' => 'js:function(){
                        $("#loading-indicator").hide();
                        $(".Tabled table").addClass("table");
                        $(".Tabled table").addClass("table-condensed");
                        updateGroupGridSelectRow();
                   }',
    'beforeAjaxUpdate'=>'js:function(){
        $("#loading-indicator").show();
    }',
    'htmlOptions' => array(
        'class' => 'Tabled',
    ),
    'cssFile' => Yii::app()->baseUrl . '/css/main.css',
    'dataProvider' => $groupModel->search(),
    'columns' => array(
        'name',
        'note',
        array(
            'header'=>'Members count',
            'value'=>'$data->usersCount',
        ),
        array(
            'header' => 'Update Group Info',
            'class' => 'CButtonColumn',
            'template' => '{options}',
            'buttons' => array(
                'options' => array(
                    'label' => '<span class="glyphicon glyphicon-pencil"></span>',
                    'url' => 'Yii::app()->createUrl("group/getUpdateForm",array("id"=>$data->id))',
                    'options' => array(
                        'class' => 'action-link',
                        'ajax'=>array(
                            'type'=>'GET',
                            'url'=>'js:$(this).attr("href")',
                            'success'=>'js:function(data){
                                $("#updateGroupModal .modal-body").html(data);
                            }',
                            'beforeSend'=>'js:function(){
                                $("#updateGroupModal .modal-body").html("Please Wait...");
                                $("#updateGroupModal").modal("show");
                            }'
                        )
                    ),
                )
            )
        ),
        array(
            'header'=>'Manage Group Users',
            'class' => 'CButtonColumn',
            'template' => '{options}',
            'buttons' => array(
                'options' => array(
                    'label' => '<span class="glyphicon glyphicon-user"></span>',
                    'url' => 'Yii::app()->createUrl("group/users",array("id"=>$data->id))',
                    'options' => array(
                        'class' => 'action-link',
                    ),
                )
            ),
        ),
        array(
            'header' => 'Delete Group',
            'class' => 'CButtonColumn',
            'template' => '{options}',
            'buttons' => array(
                'options' => array(
                    'label' => '<span class="glyphicon glyphicon-trash"></span>',
                    'url' => 'Yii::app()->createUrl("group/delete")',
                    'options' => array(
                        'class' => 'action-link',
                        'confirm'=>'Are You Sure you want to delete?',
                        'ajax'=>array(
                            'type'=>'POST',
                            'data'=>'js:{
                                "id":$(this).parent().parent().attr("group-id")
                            }',
                            'dataType'=>'json',
                            'url'=>'js:$(this).attr("href")',
                            'success'=>'js:function(data){
                                $("#deleteGroupModal .modal-body").html(data.message);
                                if(data.status){
                                    $("#group-grid").yiiGridView("update");
                                }
                            }',
                            'beforeSend'=>'js:function(){
                                $("#deleteGroupModal .modal-body").html("Please Wait...");
                                $("#deleteGroupModal").modal("show");
                            }'
                        )
                    ),
                )
            )
        ),
    ),
)); ?>

protected/views/group/partials/group-user-list.php
<?php
/**
 * Created by PhpStorm.
 * User: Dell 3521
 * Date: 07/01/15
 * Time: 05:32 م
 */

$this->widget('zii.widgets.grid.CGridView', array(
    'id' => 'user-grid',
    'summaryText' => '',
    'afterAjaxUpdate' => 'js:function(){
        	 $(".Tabled table").addClass("table");
            $(".Tabled table").addClass("table-condensed");
    }',
    'htmlOptions' => array(
        'class' => 'Tabled',
    ),
    'cssFile' => Yii::app()->baseUrl . '/css/main.css',
    'dataProvider' => $userDataProvider,
    'columns' => array(
        array(
            'class' => 'CCheckBoxColumn',
            'htmlOptions' => array('style' => 'width: 40px;'),
            'id' => 'user_id',
            'selectableRows' => 2,
            'name' => 'id',
            'disabled'=>'$data->isMemberInGroup($data->groupId)',
        ),
        'username',
        array(
            'header' => 'Delete User From Group',
            'class' => 'CButtonColumn',
            'template' => '{options}',

            'buttons' => array(
                'options' => array(
                    'label' => '<span class="glyphicon glyphicon-trash"></span>',
                    'visible'=>'$data->isMemberInGroup($data->groupId)',
                    'url' => 'Yii::app()->createUrl("group/deleteFromGroup",array("userId"=>$data->id,"groupId"=>$data->groupId))',
                    'options' => array(
                        'class' => 'action-link',
                        'confirm'=>'Are you sure you want to delete this user?',
                        'ajax' => array(
                            'url' => 'js:$(this).attr("href")',
                            'type' => 'GET',
                            'dataType'=>'json',
                            'success' => 'js:function(data){
                                            $("#deleteUserModal .modal-body").html(data.message);
                                            if(data.status){
                                                $("#user-grid").yiiGridView("update");
                                            }
                                    }',

                            'beforeSend' => 'js:function(){
                                            $("#deleteUserModal .modal-body").html("Please wait...");
                                            $("#deleteUserModal").modal("show");
                                    }'

                        ),
                    ),
                )
            )
        ),
    ),
)); ?>

protected/views/group/partials/members-list.php
<?php if(empty($members)):?>
    <div class="select-prompt">No members in this group</div>
<?php endif;?>

<?php if(!empty($members)):?>
    <ul class="member-list">
    <?php foreach($members as $member):?>
        <li><?php echo $member->username;?></li>
    <?php endforeach;?>
    </ul>
<?php endif;?>