protected/controllers/SettingController.php
<?php

class SettingController extends Controller
{
	/**
	 * @var string the default layout for the views. Defaults to '//layouts/column2', meaning
	 * using two-column layout. See 'protected/views/layouts/column2.php'.
	 */
	public $layout='//layouts/column2';

	/**
	 * @return array action filters
	 */
	public function filters()
	{
        return array(
            'checkAccess',
            'adminAccess',
        );
	}


	/**
	 * Specifies the access control rules.
	 * This method is used by the 'accessControl' filter.
	 * @return array access control rules
	 */
	public function accessRules()
	{
		return array(
			array('allow',  // allow all users to perform 'index' and 'view' actions
				'actions'=>array('index','view'),
				'users'=>array('*'),
			),
			array('allow', // allow authenticated user to perform 'create' and 'update' actions
				'actions'=>array('create','update'),
				'users'=>array('@'),
			),
			array('allow', // allow admin user to perform 'admin' and 'delete' actions
				'actions'=>array('admin','delete'),
				'users'=>array('admin'),
			),
			array('deny',  // deny all users
				'users'=>array('*'),
			),
		);
	}

	public function actionIndex()
	{
		$setting = Setting::model()->find('name=:name',array(
            ':name'=>Setting::SETTING_APP_NAME,
        ));
        if(isset($_POST['Setting'])){
            $setting->value = $_POST['Setting']['value'];

            if($setting->save()){
                $this->redirect(array('task/index'));
            }
        }
		$this->render('index',array(
			'setting'=>$setting,
		));
	}

	public function loadModel($id)
	{
		$model=Setting::model()->findByPk($id);
		if($model===null)
			throw new CHttpException(404,'The requested page does not exist.');
		return $model;
	}

    public function filterCheckAccess($chain){
        if(!Yii::app()->user->isGuest){
            $chain->run();
        }else{
            Yii::app()->request->redirect(array('site/login'));
        }
    }
    public function filterAdminAccess($chain){
        if(Yii::app()->user->checkAccess('administrator')){
            $chain->run();
        }else{
            throw new CHttpException(403);
        }
    }
}

protected/controllers/TaskController.php
<?php

class TaskController extends Controller
{
    private $_projectId;
    private $_project;
    /**
     * @var string the default layout for the views. Defaults to '//layouts/column2', meaning
     * using two-column layout. See 'protected/views/layouts/column2.php'.
     */
    public $layout = '//layouts/column2';
    public $isSupervisorOrAdministrator = false;

    /**
     * @return array action filters
     */
    public function filters()
    {
        return array(
            'checkAccess',
            'endTask +changeTaskStatusToClose',
            'reassign +changeTaskAssignment',
            'supervisorAccess +changeTaskReminded',
        );
    }

    /**
     * Specifies the access control rules.
     * This method is used by the 'accessControl' filter.
     * @return array access control rules
     */
    public function accessRules()
    {
        return array(
            array('allow', // allow all users to perform 'index' and 'view' actions
                'actions' => array('index', 'view'),
                'users' => array('*'),
            ),
            array('allow', // allow authenticated user to perform 'create' and 'update' actions
                'actions' => array('create', 'update'),
                'users' => array('@'),
            ),
            array('allow', // allow admin user to perform 'admin' and 'delete' actions
                'actions' => array('admin', 'delete'),
                'users' => array('admin'),
            ),
            array('deny', // deny all users
                'users' => array('*'),
            ),
        );
    }

    /**
     * Displays a particular model.
     * @param integer $id the ID of the model to be displayed
     */
    public function actionView($id)
    {
        $this->render('view', array(
            'model' => $this->loadModel($id),
        ));
    }

    /**
     *
     * This method does the following:
     * 1- creates a new Task model and store it in the database.
     * 2- Store the needed notifications so the notification system can do its function and notifying members & supervisors related to the Task
     * 3- Add the "creation of Task entry" to the Task Log
     * @return string
     * @dataType json
     *
     */
    public function actionCreate()
    {
        if (isset($_POST['Task'])) {
            $currentUser = User::model()->with('supervisors')->findByPk(Yii::app()->user->id);
            $currentUser->role = User::model()->getRole($currentUser->id);
            $model = new Task;
            $model->attributes = $_POST['Task'];

            $model->type = Task::TYPE_MANUAL;
            $model->second_priority = Task::SECOND_PRIORITY_NEVER;
            $model->third_priority = Task::THIRD_PRIORITY_NEVER;

            $model->reminded = Task::TASK_NOT_REMINDED;

            if (strlen($_POST['Task']['due_to_date']) > 0) {
                $model->due_to_date = date('Y-m-d',strtotime($_POST['Task']['due_to_date']));
            }
            // Set the user_id value of the Task Object
            if ($currentUser->role == User::ROLE_PROJECT_SUPERVISOR) {
                if (strlen($_POST['Task']['user_id']) != 0) {
                    $model->user_id = intval($_POST['Task']['user_id']);
                }
            } else if ($currentUser->role == User::ROLE_MEMBER) {
                $model->user_id = Yii::app()->user->id;
            }
            $successSave = $model->save();
            if ($successSave) {
                // Add to Log
                $this->addStatusLog("<span style='color: #000;'>".Yii::app()->user->username." :</span> <span style='color: #5C5C5C;'>Create</span>  <span class='glyphicon glyphicon-arrow-right'></span> ".$model->user->username . " <span style='color: #000;'>|</span> " . date('j-m-Y h:i A', strtotime($model->create_date)), $model->id);
                // Set the notification
                if ($currentUser->role == User::ROLE_PROJECT_SUPERVISOR) {
                    // Supervisor may assign task to him self
                    if($model->user_id!=$currentUser->id){
                        $model->notified = Task::USER_NOT_NOTIFIED;
                    }else{
                        $model->notified = Task::USER_NOTIFIED;
                    }
                    $model->save(false);
                    $supervisors = User::model()->with('supervisors')->findByPk($model->user_id)->supervisors;
                    foreach ($supervisors as $supervisorUser) {
                        if ($supervisorUser->id != $currentUser->id) {
                            $supervisorNotification = new SupervisorNotification;
                            $supervisorNotification->task_id = $model->id;
                            $supervisorNotification->supervisor_id = $supervisorUser->id;
                            $supervisorNotification->supervisor_notified = SupervisorNotification::SUPERVISOR_NOT_NOTIFIED;
                            $supervisorNotification->project_id = $currentUser->current_project_id;
                            $supervisorNotification->update_type = SupervisorNotification::UPDATE_TYPE_TASK_CREATE;
                            $supervisorNotification->save();
                        }
                    }
                } else if ($currentUser->role == User::ROLE_MEMBER) {
                    $model->notified = Task::USER_NOTIFIED;
                    $model->save(false);
                    $currentUserSupervisors = $currentUser->supervisors;
                    foreach ($currentUserSupervisors as $supervisorUser) {
                        $supervisorNotification = new SupervisorNotification;
                        $supervisorNotification->project_id = $currentUser->current_project_id;
                        $supervisorNotification->task_id = $model->id;
                        $supervisorNotification->supervisor_id = $supervisorUser->id;
                        $supervisorNotification->supervisor_notified = SupervisorNotification::SUPERVISOR_NOT_NOTIFIED;
                        $supervisorNotification->update_type = SupervisorNotification::UPDATE_TYPE_TASK_CREATE;
                        $supervisorNotification->save();
                    }
                }else if($currentUser->role == User::ROLE_ADMIN){
                    // Admin may assign task to him self
                    if($model->user_id!=$currentUser->id){
                        $model->notified = Task::USER_NOT_NOTIFIED;
                    }else{
                        $model->notified = Task::USER_NOTIFIED;
                    }
                    $model->save(false);
                    $supervisors = User::model()->with('supervisors')->findByPk($model->user_id)->supervisors;
                    foreach ($supervisors as $supervisorUser) {
                        if ($supervisorUser->id != $currentUser->id) {
                            $supervisorNotification = new SupervisorNotification;
                            $supervisorNotification->task_id = $model->id;
                            $supervisorNotification->supervisor_id = $supervisorUser->id;
                            $supervisorNotification->supervisor_notified = SupervisorNotification::SUPERVISOR_NOT_NOTIFIED;
                            $supervisorNotification->project_id = $currentUser->current_project_id;
                            $supervisorNotification->update_type = SupervisorNotification::UPDATE_TYPE_TASK_CREATE;
                            $supervisorNotification->save();
                        }
                    }
                }
                echo CJSON::encode(array(
                    'status' => $successSave,
                    'message' => 'Serial No: '.$model->serial_no,
                    'id' => $model->id,
                ));
            } else {
                echo CJSON::encode(array(
                    'status' => $successSave,
                    'message' => "Could not add the task.",
                ));
            }
        }
    }


    public function actionEmpty(){
        $this->render('empty');
    }
    /**
     * This method renders the main Task Manager screen
     */
    public function actionIndex()
    {
        // Force Default Order
        $forceDefaultToDoTasksOrder = true;
        $forceDefaultFollowUpTasksOrder = true;
        $forceDefaultCompleteTasksOrder = true;
        $forceDefaultArchivedTasksOrder = true;

        if (isset($_GET['sort']) && strlen($_GET['sort']) > 0) {
            if ($_GET['ajax'] == 'follow-up-task-grid') {
                $forceDefaultFollowUpTasksOrder = false;
            }
            if ($_GET['ajax'] == 'task-grid') {
                $forceDefaultToDoTasksOrder = false;
            }
            if ($_GET['ajax'] == 'complete-task-grid') {
                $forceDefaultCompleteTasksOrder = false;
            }
            if ($_GET['ajax'] == 'archived-task-grid') {
                $forceDefaultArchivedTasksOrder = false;
            }
        }

        // For the Task create Form
        $model = new Task;
        //Get the current user model
        $currentUser = User::model()->findByPk(Yii::app()->user->id);
        $currentUser->role = $currentUser->getRole($currentUser->id);
        // Check current user row and save the state to the controller
        $this->isSupervisorOrAdministrator = $currentUser->role == User::ROLE_PROJECT_SUPERVISOR || $currentUser->role == User::ROLE_ADMIN ? true : false;
        //Create the todo Task model search criteria
        $taskModel = new Task('search');
        $taskModel->unsetAttributes();
        //Create the complete Task model search criteria
        $completeTaskList = new Task('search');
        $completeTaskList->unsetAttributes();
        $completeTaskList->status = Task::STATE_COMPLETE;
        $taskModel->status = array(Task::STATE_NOT_READ, Task::STATE_INCOMPLETE);

        $followTaskModel = new Task('search');
        $followTaskModel->unsetAttributes();

protected/views/layouts/column1.php
<?php /* @var $this Controller */ ?>
<?php $this->beginContent('//layouts/main'); ?>
<div id="content">
	<?php echo $content; ?>
</div><!-- content -->
<?php $this->endContent(); ?>

protected/views/layouts/column2.php
<?php /* @var $this Controller */ ?>
<?php $this->beginContent('//layouts/main'); ?>
<div class="row">
	<div class="col-md-12" id="content">
		<?php echo $content; ?>
	</div><!-- content -->
</div>

<?php $this->endContent(); ?>

protected/views/layouts/main.php
<?php /* @var $this Controller */

$setting = Setting::model()->find('name=:name',array(
    ':name'=>Setting::SETTING_APP_NAME,
));
?>
<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en">
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
    <meta name="language" content="en"/>
    <meta name="description" content="">
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no">
    <!-- Core Script Files -->
    <script type="text/javascript" src="<?php echo Yii::app()->request->baseUrl; ?>/js/jquery.js"></script>

    <link rel="stylesheet" type="text/css" href="<?php echo Yii::app()->request->baseUrl; ?>/css/main.css"/>
    <link rel="stylesheet" type="text/css" href="<?php echo Yii::app()->request->baseUrl; ?>/css/bootstrap.min.css"/>
    <link rel="stylesheet" type="text/css" href="<?php echo Yii::app()->request->baseUrl; ?>/css/styles.css"/>

    <link rel="stylesheet" type="text/css" href="<?php echo Yii::app()->request->baseUrl; ?>/css/font-awesome.css"/>

    <?php Yii::app()->clientScript->registerScriptFile(Yii::app()->baseUrl . "/js/main.js", CClientScript::POS_END); ?>
    <title><?php echo $setting->value; ?></title>

</head>
<body>
<!-- Fixed navbar -->
<nav
    style="display: <?php echo Yii::app()->controller->id == "task" && Yii::app()->controller->action->id == "index" ? "none" : "block"; ?>"
    class="navbar navbar-static" role="navigation">
    <div id="loading-indicator" style="display: none;">
        <span>Loading, please wait ...</span>
    </div>
    <div class="container">
        <?php if (!Yii::app()->user->isGuest): ?>
            <div class="navbar-header">
                <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar"
                        aria-expanded="false" aria-controls="navbar">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
            </div>
            <div id="navbar" class="collapse navbar-collapse">
                <ul class="nav navbar-nav no-hover">
                    <li><?php echo CHtml::link($setting->value,'',array(
                            'id'=>'app-name-link',
                        ));?>
                    </li>
                    <?php
                        $user = User::model()->findByPk(Yii::app()->user->id);
                        if ($user->current_project_id != 0) {
                            $project = Project::model()->findByPk($user->current_project_id);
                            if(!is_null($project)){
                                $projectName = $project->name;
                            }else{
                                $projectName = "All-Workspaces";
                            }

                        } else {
                            $projectName = "All-Workspaces";
                        }
                    ?>


                    <li class="dropdown">
                        <a href="#" class="dropdown-toggle large-nav-text nav-link" data-toggle="dropdown" role="button"
                           aria-expanded="false"><?php echo $projectName; ?><span
                                class="caret"></span></a>
                        <?php
                        $projects = Project::model()->findAll();
                        ?>
                        <ul class="dropdown-menu" role="menu">
                            <li><?php echo CHtml::link("All-Workspaces", $this->createUrl("task/index", array('project_id' => 0))) ?></li>
                            <li class="divider"></li>
                            <?php foreach ($projects as $project): ?>
                                <li><?php echo CHtml::link($project->name, Yii::app()->createUrl('task/index', array('project_id' => $project->id))); ?></li>
                            <?php endforeach; ?>
                        </ul>
                    </li>

                </ul>

                <ul class="nav navbar-nav navbar-right" class="navbar-font-icon">
                    <?php if (!Yii::app()->user->isGuest): ?>
                        <li><?php echo CHtml::link('<i class="fa fa-sign-out"></i>', array('site/logout'), array(
                                'style' => 'font-size: 21px;',
                                'class'=>'nav-link',
                            )); ?></li>
                    <?php endif; ?>
                    <?php if (Yii::app()->user->isGuest): ?>
                        <li><?php echo CHtml::link('Login', array('site/login')); ?></li>
                    <?php endif; ?>
                </ul>
                <ul class="nav navbar-nav navbar-right" class="navbar-font-icon">
                    <li class="dropdown">
                        <a href="#" class="dropdown-toggle" id="userStatusLabel" data-toggle="dropdown" role="button"
                           aria-expanded="false"><span
                                class="connection_status"> </span><span class="caret"> </span></a>
                        <ul class="dropdown-menu" role="menu">
                            <li class="connection_status_option" status_code="<?php echo User::STATE_ONLINE ?>"><a
                                    href="#"><span
                                        class="connection_status connection_status_online"></span> Online</a></li>
                            <li class="connection_status_option" status_code="<?php echo User::STATE_BREAK ?>"><a
                                    href="#"><span class="connection_status connection_status_break"></span> Break</a>
                            </li>
                        </ul>
                    </li>
                </ul>
                <?php if (!Yii::app()->user->isGuest && User::model()->isAdmin(Yii::app()->user->id)): ?>
                <ul class="nav navbar-nav navbar-right">
                        <li class="dropdown">
                            <a href="#" class="dropdown-toggle nav-link" data-toggle="dropdown" role="button"
                               aria-expanded="false"><span class="glyphicon glyphicon-cog" style="font-size: 21px;"></span></a>
                            <ul class="dropdown-menu" role="menu">
                                <li><?php echo CHtml::link('manage Users', array('user/index')); ?></li>
                                <li><?php echo CHtml::link('manage Groups', array('group/index')); ?></li>
                                <li><?php echo CHtml::link('manage Workspaces', array('project/index')); ?></li>
                                <?php if(Yii::app()->user->checkAccess('manage_auto_tasks')):?>
                                    <li><?php echo CHtml::link('Manage Auto Tasks', array('autoTask/index')); ?></li>
                                <?php endif;?>
                                <?php if(Yii::app()->user->checkAccess('view_report')):?>
                                    <li><?php echo CHtml::link('Reports', array('project/report')); ?></li>
                                <?php endif;?>
                                <li><?php echo CHtml::link('Settings', array('setting/index')); ?></li>
                            </ul>
                        </li>

                </ul>
                <?php endif; ?>
                <?php if (!Yii::app()->user->isGuest && !User::model()->isAdmin(Yii::app()->user->id)): ?>
                    <ul class="nav navbar-nav navbar-right">

                        <li class="dropdown">
                            <a href="#" class="dropdown-toggle nav-link" data-toggle="dropdown" role="button"
                               aria-expanded="false"><span class="glyphicon glyphicon-cog" style="font-size: 21px;"></span></a>
                            <ul class="dropdown-menu" role="menu">
                                <?php if(Yii::app()->user->checkAccess('manage_auto_tasks')):?>
                                    <li><?php echo CHtml::link('Manage Auto Tasks', array('autoTask/index')); ?></li>
                                <?php endif;?>
                                <?php if(Yii::app()->user->checkAccess('view_report')):?>
                                    <li><?php echo CHtml::link('Reports', array('project/report')); ?></li>
                                <?php endif;?>
                                <li><?php echo CHtml::link('Reset Password', array('user/memberPasswordReset','id'=>User::model()->findByPk(Yii::app()->user->id)->id)); ?></li>
                            </ul>
                        </li>

                    </ul>
                <?php endif; ?>
                <ul class="nav navbar-nav navbar-right no-hover">
                    <li><a class="large-nav-text"><?php echo !Yii::app()->user->isGuest ? Yii::app()->user->username : "Projstar"; ?></a></li>
                </ul>
            </div>
            <!--/.nav-collapse -->
        <?php endif; ?>
    </div>
</nav>
<div class="container-fluid content" style="min-height: 530px;">
    <?php echo $content; ?>
</div>
<hr/>

<!-- script files -->
<script type="text/javascript" src="<?php echo Yii::app()->request->baseUrl; ?>/js/bootstrap.min.js"></script>
<script type="text/javascript" src="<?php echo Yii::app()->request->baseUrl; ?>/js/scripts.js"></script>

<?php if (!Yii::app()->user->isGuest): ?>
    <?php
    $currentUser = User::model()->findByPk(Yii::app()->user->id);

    Yii::app()->clientScript->registerScript('user_status', '
    var statusCssClassArray = ["connection_status_break","connection_status_online","connection_status_offline"];
    var statusCode = '.$currentUser->status.';

    $(function(){
        $("#userStatusLabel span.connection_status").addClass(statusCssClassArray[statusCode]);
    });
    $(".connection_status_option").click(function( event ){
        $.ajax({
            "url":' . CJavaScript::encode(Yii::app()->createUrl('user/changeStatus')) . ',
            "data":{
                status_code:$(this).attr("status_code")
            },
            "type":"post",
            "dataType":"json",
            "success":function(data){
                if(data.status){
                    $("#userStatusLabel span.connection_status").removeClass(statusCssClassArray[data.p_status_code]);
                    $("#userStatusLabel span.connection_status").addClass(statusCssClassArray[data.status_code]);
                    $("#user-grid").yiiGridView("update");
                }
            }
        });
    });

');
    ?>
<?php endif; ?>
</body>
</html>