protected/models/Project.php
<?php

/**
 * This is the model class for table "tbl_project".
 *
 * The followings are the available columns in table 'tbl_project':
 * @property integer $id
 * @property string $name
 * @property string $description
 * @property string $create_date
 * @property integer $create_id
 * @property string $update_date
 * @property integer $update_id
 * @property string $note
 *
 * The followings are the available model relations:
 * @property ProjectUserAssignment[] $projectUserAssignments
 * @property Task[] $tasks
 * @property integer $pendingTasksNo
 * @property integer $onGoingTasksNo
 * @property integer $holdTasksNo
 * @property integer $completedTasksNo
 * @property Task[] $pendingTasks
 * @property Task[] $onGoingTasks
 * @property Task[] $holdTasks
 * @property Task[] $completedTasks members
 * @property User[] members
 */
class Project extends ProjStarActiveRecord
{

	/**
	 * @return string the associated database table name
	 */
	public function tableName()
	{
		return 'tbl_project';
	}

	/**
	 * @return array validation rules for model attributes.
	 */
	public function rules()
	{
		// NOTE: you should only define rules for those attributes that
		// will receive user inputs.
		return array(
			array('name', 'required'),
            array('name', 'unique'),
			array('create_id, update_id', 'numerical', 'integerOnly'=>true),
			array('name', 'length', 'max'=>255),
			array('description, note', 'safe'),
			// The following rule is used by search().
			// @todo Please remove those attributes that should not be searched.
			array('id, name, description, create_date, create_id, update_date, update_id, note', 'safe', 'on'=>'search'),
		);
	}

    /**
	 * @return array relational rules.
	 */

    public function relations()
	{
		// NOTE: you may need to adjust the relation name and the related
		// class name for the relations automatically generated below.
		return array(
			'projectUserAssignments' => array(self::HAS_MANY, 'ProjectUserAssignment', 'project_id'),
			'tasks' => array(self::HAS_MANY, 'Task', 'project_id'),
            'tasksCount' => array(self::STAT, 'Task', 'project_id'),
            'archivedTasksCount' => array(self::STAT, 'Task', 'project_id','condition'=>'status=:status','params'=>array(
                ':status'=>Task::STATE_VERIFIED,
            )),
            'usersCount' => array(self::STAT, 'User', 'tbl_project_user_assignment(project_id,user_id)'),
            /*'pendingTasksNo' => array(self::STAT,'Task','project_id','condition' => 'status=:status', 'params' => array(':status' => Task::STATE_PENDING)),
            'onGoingTasksNo' => array(self::STAT,'Task','project_id','condition' => 'status=:status', 'params' => array(':status' => Task::STATE_ON_GOING)),
            'holdTasksNo' => array(self::STAT,'Task','project_id','condition' => 'status=:status', 'params' => array(':status' => Task::STATE_HOLD)),
            'completedTasksNo' => array(self::STAT,'Task','project_id','condition' => 'status=:status', 'params' => array(':status' => Task::STATE_COMPLETE)),
            'pendingTasks' => array(self::HAS_MANY,'Task','project_id','condition' => 'status=:status', 'params' => array(':status' => Task::STATE_PENDING)),
            'onGoingTasks' => array(self::HAS_MANY,'Task','project_id','condition' => 'status=:status', 'params' => array(':status' => Task::STATE_ON_GOING)),
            'holdTasks' => array(self::HAS_MANY,'Task','project_id','condition' => 'status=:status', 'params' => array(':status' => Task::STATE_HOLD)),
            'completedTasks' => array(self::HAS_MANY,'Task','project_id','condition' => 'status=:status', 'params' => array(':status' => Task::STATE_COMPLETE)),*/
            'members'=>array(self::MANY_MANY,'User','tbl_project_user_assignment(project_id,user_id)'),
            'membersCount'=>array(self::STAT,'User','tbl_project_user_assignment(project_id,user_id)'),
        );
	}

	/**
	 * @return array customized attribute labels (name=>label)
	 */
	public function attributeLabels()
	{
		return array(
			'id' => 'ID',
			'name' => 'Workspace Name',
			'description' => 'Workspace Description',
			'create_date' => 'Create Date',
			'create_id' => 'Create',
			'update_date' => 'Update Date',
			'update_id' => 'Update',
			'note' => 'Note',
		);
	}

    public static function getReportOptionsArray(){
        return array(
            self::REPORT_TYPE_CREATE_TASK=>'Created Tasks',
            self::REPORT_TYPE_COMPLETE_TASK=>'Completed Tasks',
            self::REPORT_TYPE_NOT_COMPLETE_TASK=>'Revision Counts',
            self::REPORT_TYPE_END_TASK=>'Ended Tasks',
        );
    }

    public function isDeletable(){
        $isDeletable = true;
        if($this->usersCount!=0){
            if($this->tasksCount != $this->archivedTasksCount){
                $isDeletable = false;
            }else{
                $isDeletable = true;
            }
        }
        return $isDeletable;
    }

    public function getMembersList(){
        return CHtml::listData($this->members,'id','username');
    }

    public static function getProjectsList(){
        return CHtml::listData(Project::model()->findAll(),'id','name');
    }

    public function getNote(){
        if(strlen($this->note)==0){
            return "No Note Available";
        }else{
            return $this->note;
        }
    }
    public function getDescription(){
        if(strlen($this->description)==0){
            return "No Description Available";
        }else{
            return $this->description;
        }
    }

    public function getProjectList($userRoleType,$user){
        if($userRoleType==User::ROLE_ADMIN){
            $projects = Project::model()->findAll();
        }else{
            $projects = $user->projects;
        }
        return CHtml::listData($projects,'id','name');
    }
    public function getProjectListForSearch(){
        $projects = Project::model()->findAll();
        return CHtml::listData($projects,'id','name');
    }

	public function search()
	{
		// @todo Please modify the following code to remove attributes that should not be searched.
		$criteria=new CDbCriteria;
		$criteria->compare('id',$this->id);
		$criteria->compare('name',$this->name,true);
		$criteria->compare('description',$this->description,true);
		$criteria->compare('create_date',$this->create_date,true);
		$criteria->compare('create_id',$this->create_id);
		$criteria->compare('update_date',$this->update_date,true);
		$criteria->compare('update_id',$this->update_id);
		$criteria->compare('note',$this->note,true);

		return new CActiveDataProvider($this, array(
			'criteria'=>$criteria,
		));
	}

    public function addMember($userId){
        try{
            Yii::app()->db->createCommand()->insert('tbl_project_user_assignment',array(
                'user_id'=>$userId,
                'project_id'=>$this->id,
            ));
        }catch(CDbException $e){

        }

    }
    public function deleteMember($userId){
        try{
            Yii::app()->db->createCommand()->delete('tbl_project_user_assignment',"user_id=:user_id AND project_id=:project_id",array(
                ':user_id'=>$userId,
                ':project_id'=>$this->id,
            ));
        }catch(CDbException $e){

        }
    }
	/**
	 * Returns the static model of the specified AR class.
	 * Please note that you should have this exact method in all your CActiveRecord descendants!
	 * @param string $className active record class name.
	 * @return Project the static model class
	 */
	public static function model($className=__CLASS__)
	{
		return parent::model($className);
	}
}

protected/controllers/ProjectController.php
<?php

class ProjectController extends Controller
{
    /**
     * @var string the default layout for the views. Defaults to '//layouts/column2', meaning
     * using two-column layout. See 'protected/views/layouts/column2.php'.
     */
    public $layout = '//layouts/column2';
    /**
     * @return array action filters
     */
    public function filters()
    {
        return array(
            'checkAccess',
            'adminAccess -report,getReportData',
            'viewReportAccess +report,getReportData',
        );
    }

    /**
     * Displays a particular model.
     * @param integer $id the ID of the model to be displayed
     */
    public function actionView($id)
    {
        $this->pageTitle = "Control Panel - Workspace: ";
        $projectModel = $this->loadModel($id);
        $userDataProvider = new CActiveDataProvider('User');
        $users = $projectModel->members;

        foreach ($users as $user) {
            $user->projectId = $projectModel->id;
        }

        $userDataProvider->setData($users);
        $tasks = $projectModel->tasks;
        $incompleteTaskCount = 0;
        $completeTaskCount = 0;
        $archivedTaskCount = 0;
        $notReadTaskCount = 0;

        foreach($tasks as $task){
            switch($task->status){
                case Task::STATE_NOT_READ:
                    $notReadTaskCount +=1;
                    break;
                case Task::STATE_INCOMPLETE:
                    $incompleteTaskCount +=1;
                    break;
                case Task::STATE_COMPLETE:
                    $completeTaskCount +=1;
                    break;
                case Task::STATE_VERIFIED:
                    $archivedTaskCount +=1;
                    break;
            }
        }

        $this->render('view', array(
            'projectModel' => $projectModel,
            'userDataProvider' => $userDataProvider,
            'notReadTaskCount'=>$notReadTaskCount,
            'incompleteTaskCount'=>$incompleteTaskCount,
            'completeTaskCount'=>$completeTaskCount,
            'archivedTaskCount'=>$archivedTaskCount,
            'taskCount'=>count($projectModel->tasks),
        ));
    }

    /**
     * Creates a new model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     */


    public function actionCreate()
    {
        $model = new Project;
        if (isset($_POST['Project'])) {
            $model->name = $_POST['Project']['name'];
            $model->description = $_POST['Project']['description'];
            $model->note = $_POST['Project']['note'];
            if ($model->save()) {
                if (isset($_POST['user_id'])) {
                    foreach ($_POST['user_id'] as $userId) {
                        $model->addMember($userId);
                    }
                }
                echo CJSON::encode(array(
                    'status' => true,
                    'message' => 'A new Workspace was Added to the workspace\'s list!',
                ));
            } else {
                echo CJSON::encode(array(
                    'status' => false,
                    'message' => "Could not add a new Workspace to the system",
                ));
            }
        }
    }

    /**
     * Updates a particular model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param integer $id the ID of the model to be updated
     */
    public function actionUpdate($id, $ref)
    {
        $model = $this->loadModel($id);
        $userDataProvider = new CActiveDataProvider('User');
        $users = User::model()->findAll();
        foreach ($users as $user) {
            $user->projectId = $model->id;
        }
        $userDataProvider->setData($users);
        // Uncomment the following line if AJAX validation is needed
        // $this->performAjaxValidation($model);

        if (isset($_POST['Project'])) {
            $model->attributes = $_POST['Project'];
            if ($model->save()) {
                if (isset($_POST['user_id'])) {
                    foreach ($_POST['user_id'] as $userId) {
                        $model->addMember($userId);
                    }
                }
                $this->redirect(array('index'));
            }

        }

        $this->render('update', array(
            'projectModel' => $model,
            'ref' => $ref,
            'userDataProvider' => $userDataProvider,
        ));
    }

    public function actionTest()
    {
        $count = Task::model()->count('YEAR(create_date)=:date',array(
            ':date'=>date('Y'),
        ));
        echo $count;
    }

    public function actionReport()
    {
        $report = new ReportModel;
        $this->render('tasks_report', array(
            'report' => $report,
        ));
    }

    public function actionGetReportData()
    {
        if (Yii::app()->request->isAjaxRequest) {
            $reportModel = new ReportModel;
            $reportModel->attributes = $_GET['ReportModel'];
            if ($reportModel->validate()) {
                echo CJSON::encode(array(
                    'status' => true,
                    'reportDate' => $this->generateReport($reportModel),
                ));
            } else {
                echo CJSON::encode(array(
                    'status' => false,
                ));
            }
        }
    }

    public function generateReport($reportModel)
    {
        $project = Project::model()->with('members')->findByPk($reportModel->project_id);
        $dataPoints = array();
        $title = "";
        $legendText = "";
        switch ($reportModel->report_option) {
            case ReportModel::REPORT_TYPE_CREATE_TASK:
                $title = "New Tasks Report for " . $project->name . " workspace";
                $legendText = "Tasks Count";
                $dataPoints = $this->generateCreateTasksDataPoints($reportModel, $project);
                break;
            case ReportModel::REPORT_TYPE_COMPLETE_TASK:
                $title = "Completed Tasks Report for " . $project->name . " workspace";
                $dataPoints = $this->generateCompletedTasksDataPoints($reportModel, $project);
                $legendText = "Tasks Count";
                break;
            case ReportModel::REPORT_TYPE_END_TASK:
                $title = "Ended Tasks Report for " . $project->name . " workspace";
                $dataPoints = $this->generateEndedTasksDataPoints($reportModel, $project);
                $legendText = "Tasks Count";
                break;
            case ReportModel::REPORT_TYPE_NOT_COMPLETE_TASK:
                $title = "Revision Tasks Report for " . $project->name . " workspace";
                $dataPoints = $this->generateNotCompletedTasksDataPoints($reportModel, $project);
                $legendText = "Tasks Count";
                break;
        }
        if($reportModel->report_option==ReportModel::REPORT_TYPE_NOT_COMPLETE_TASK){
            $reportData = array(
                'title' => array(
                    'text' => $title,
                ),
                'animationEnabled' => true,
                'axisX' => array(
                    'interval' => 1,
                    'gridThickness' => 0,
                    'labelFontSize' => 14,
                    'labelFontStyle' => 'normal',
                    'labelFontWeight' => 'normal',
                    'labelFontFamily' => 'Lucida Sans Unicode',
                ),
                'axisY2' => array(
                    'interlacedColor' => 'rgba(1,77,101,.2)',
                    'gridColor' => 'rgba(1,77,101,.1)',
                ),
                'data' => array(
                    array(
                        'type' => 'bar',
                        'name' => 'companies',
                        'axisYType' => "secondary",
                        'color' => '#014D65',
                        'dataPoints' => $dataPoints[0],
                    ),
                    array(
                        'type' => 'bar',
                        'name' => 'companies',
                        'axisYType' => "secondary",
                        'color' => '#FF0000',
                        'dataPoints' => $dataPoints[1],
                    )
                ),
            );
        }else{
            $reportData = array(
                'title' => array(
                    'text' => $title,
                ),
                'animationEnabled' => true,
                'axisX' => array(
                    'interval' => 1,
                    'gridThickness' => 0,
                    'labelFontSize' => 14,
                    'labelFontStyle' => 'normal',
                    'labelFontWeight' => 'normal',
                    'labelFontFamily' => 'Lucida Sans Unicode',
                ),
                'axisY2' => array(
                    'interlacedColor' => 'rgba(1,77,101,.2)',
                    'gridColor' => 'rgba(1,77,101,.1)',
                ),
                'data' => array(
                    array(
                        'type' => 'bar',
                        'name' => 'companies',
                        'axisYType' => "secondary",
                        'color' => '#014D65',
                        'dataPoints' => $dataPoints,
                    ),
                ),
            );
        }
        return $reportData;
    }

    public function generateCreateTasksDataPoints($reportModel, $project)
    {
        $dataPoints = array();
        $members = $project->members(array(
            'with'=>array(
                'tasks'=>array(
                    'alias'=>'task',
                    'select'=>'count(*) as count',
                    'condition' => '(task.create_date BETWEEN :from_date AND :to_date) AND task.status IN(' . implode(',', array(
                            Task::STATE_COMPLETE,
                            Task::STATE_INCOMPLETE,
                            Task::STATE_NOT_READ,

protected/views/project/_search.php
<?php
/* @var $this ProjectController */
/* @var $model Project */
/* @var $form CActiveForm */
?>

<div class="wide form">

<?php $form=$this->beginWidget('CActiveForm', array(
	'action'=>Yii::app()->createUrl($this->route),
	'method'=>'get',
)); ?>

	<div class="row">
		<?php echo $form->label($model,'id'); ?>
		<?php echo $form->textField($model,'id'); ?>
	</div>

	<div class="row">
		<?php echo $form->label($model,'name'); ?>
		<?php echo $form->textField($model,'name',array('size'=>60,'maxlength'=>255)); ?>
	</div>

	<div class="row">
		<?php echo $form->label($model,'description'); ?>
		<?php echo $form->textArea($model,'description',array('rows'=>6, 'cols'=>50)); ?>
	</div>

	<div class="row">
		<?php echo $form->label($model,'create_date'); ?>
		<?php echo $form->textField($model,'create_date'); ?>
	</div>

	<div class="row">
		<?php echo $form->label($model,'create_id'); ?>
		<?php echo $form->textField($model,'create_id'); ?>
	</div>

	<div class="row">
		<?php echo $form->label($model,'update_date'); ?>
		<?php echo $form->textField($model,'update_date'); ?>
	</div>

	<div class="row">
		<?php echo $form->label($model,'update_id'); ?>
		<?php echo $form->textField($model,'update_id'); ?>
	</div>

	<div class="row">
		<?php echo $form->label($model,'note'); ?>
		<?php echo $form->textArea($model,'note',array('rows'=>6, 'cols'=>50)); ?>
	</div>

	<div class="row buttons">
		<?php echo CHtml::submitButton('Search'); ?>
	</div>

<?php $this->endWidget(); ?>

</div><!-- search-form -->

protected/views/project/_view.php
<?php
/* @var $this ProjectController */
/* @var $data Project */
?>

<div class="view">

	<b><?php echo CHtml::encode($data->getAttributeLabel('id')); ?>:</b>
	<?php echo CHtml::link(CHtml::encode($data->id), array('view', 'id'=>$data->id)); ?>
	<br />

	<b><?php echo CHtml::encode($data->getAttributeLabel('name')); ?>:</b>
	<?php echo CHtml::encode($data->name); ?>
	<br />

	<b><?php echo CHtml::encode($data->getAttributeLabel('description')); ?>:</b>
	<?php echo CHtml::encode($data->description); ?>
	<br />

	<b><?php echo CHtml::encode($data->getAttributeLabel('create_date')); ?>:</b>
	<?php echo CHtml::encode($data->create_date); ?>
	<br />

	<b><?php echo CHtml::encode($data->getAttributeLabel('create_id')); ?>:</b>
	<?php echo CHtml::encode($data->create_id); ?>
	<br />

	<b><?php echo CHtml::encode($data->getAttributeLabel('update_date')); ?>:</b>
	<?php echo CHtml::encode($data->update_date); ?>
	<br />

	<b><?php echo CHtml::encode($data->getAttributeLabel('update_id')); ?>:</b>
	<?php echo CHtml::encode($data->update_id); ?>
	<br />

	<?php /*
	<b><?php echo CHtml::encode($data->getAttributeLabel('note')); ?>:</b>
	<?php echo CHtml::encode($data->note); ?>
	<br />

	*/ ?>

</div>

protected/views/project/admin.php
<?php
/* @var $this ProjectController */
/* @var $model Project */

$this->breadcrumbs=array(
	'Projects'=>array('index'),
	'Manage',
);

$this->menu=array(
	array('label'=>'List Project', 'url'=>array('index')),
	array('label'=>'Create Project', 'url'=>array('create')),
);

Yii::app()->clientScript->registerScript('search', "
$('.search-button').click(function(){
	$('.search-form').toggle();
	return false;
});
$('.search-form form').submit(function(){
	$('#project-grid').yiiGridView('update', {
		data: $(this).serialize()
	});
	return false;
});
");
?>

<h1>Manage Projects</h1>

<p>
You may optionally enter a comparison operator (<b>&lt;</b>, <b>&lt;=</b>, <b>&gt;</b>, <b>&gt;=</b>, <b>&lt;&gt;</b>
or <b>=</b>) at the beginning of each of your search values to specify how the comparison should be done.
</p>

<?php echo CHtml::link('Advanced Search','#',array('class'=>'search-button')); ?>
<div class="search-form" style="display:none">
<?php $this->renderPartial('_search',array(
	'model'=>$model,
)); ?>
</div><!-- search-form -->

<?php $this->widget('zii.widgets.grid.CGridView', array(
	'id'=>'project-grid',
	'dataProvider'=>$model->search(),
	'filter'=>$model,
	'columns'=>array(
		'id',
		'name',
		'description',
		'create_date',
		'create_id',
		'update_date',
		/*
		'update_id',
		'note',
		*/
		array(
			'class'=>'CButtonColumn',
		),
	),
)); ?>

protected/views/project/create.php
<?php
/* @var $this ProjectController */
/* @var $model Project */

$this->breadcrumbs=array(
	'Projects'=>array('index'),
	'Create',
);

$this->menu=array(
	array('label'=>'List Project', 'url'=>array('index')),
	array('label'=>'Manage Project', 'url'=>array('admin')),
);
?>

<h1>Create Project</h1>

<?php $this->renderPartial('_form', array('model'=>$model)); ?>

protected/views/project/index.php
<?php
/* @var $this ProjectController */
/* @var $dataProvider CActiveDataProvider */
Yii::app()->clientScript->registerScript('project-grid-script', "
$(function(){
        $('.Tabled table').addClass('table');
});
",CClientScript::POS_END);

$this->widget('application.components.Ajaxmodal', array(
    'name' => 'createProjectModal',
    'title' => 'Create a new Workspace',
    'width' => '80px',
));

$this->widget('application.components.Ajaxmodal', array(
    'name' => 'statusModal',
    'title' => 'Status',
    'width' => '600px',
));
$this->widget('application.components.Ajaxmodal', array(
    'name' => 'deleteWorkspaceModal',
    'title' => 'Status',
    'width' => '600px',
));
?>

<?php echo CHtml::ajaxButton("Create Workspace",$this->createUrl('getCreateForm',array('ref'=>'p_index')),array(
        'type'=>'GET',
        'success'=>'js:function(data){
            $("#createProjectModal .modal-body").html(data);

        }',
        'beforeSend'=>'js:function(){
            $("#createProjectModal .modal-body").html("Please Wait...");
            $("#createProjectModal").modal("show");
        }'
    ),
    array(
        'id'=>'link-'.uniqid(),
        'class'=>'btn btn-success btn-sm',
    ));
?>
<hr/>


<div class="row">
    <div class="col-md-12">
        <?php $this->widget('zii.widgets.grid.CGridView', array(
            'id' => 'project-grid',
            'summaryText' => '<span>Total No Of Workspaces: {count}</span><br/>',
            'afterAjaxUpdate' => 'js:function(){
        	$(".Tabled table").addClass("table");
         }',
            'htmlOptions' => array(
                'class' => 'Tabled',
            ),
            'cssFile' => Yii::app()->baseUrl . '/css/main.css',
            'dataProvider' => $dataProvider,
            'columns' => array(
                'name',
                array(
                    'header'=>'members count',
                    'value'=>'$data->membersCount',
                ),

                array(
                    'name'=>'create_date',
                    'value'=>'date("d-m-Y",strtotime($data->create_date))'
                ),
                'description',
                'note',
                array(
                    'header' => 'Edit',
                    'class' => 'CButtonColumn',
                    'template' => '{options}',
                    'buttons' => array(
                        'options' => array(
                            'label' => '<span class="glyphicon glyphicon-pencil"></span>',
                            'url' => 'Yii::app()->createUrl("project/update",array("id"=>$data->id,"ref"=>"p_index"))',
                            'options' => array(
                                'class' => 'action-link',
                            ),
                        )
                    )
                ),
                array(
                    'header' => 'Delete Workspace',
                    'class' => 'CButtonColumn',
                    'template' => '{options}',
                    'buttons' => array(
                        'options' => array(
                            'label' => '<span class="glyphicon glyphicon-trash"></span>',
                            'visible'=>'$data->isDeletable()',
                            'url' => 'Yii::app()->createUrl("project/delete",array("id"=>$data->id))',
                            'options' => array(
                                'class' => 'action-link',
                                'confirm'=>'Are you sure you want to delete this workspace?',
                                'ajax' => array(
                                    'url' => 'js:$(this).attr("href")',
                                    'type' => 'POST',
                                    'dataType'=>'json',
                                    'success' => 'js:function(data){
                                            alert(data.status);
                                            $("#deleteWorkspaceModal .modal-body").html(data.message);
                                            if(data.status){
                                                $("#project-grid").yiiGridView("update");
                                            }
                                    }',
                                    'beforeSend' => 'js:function(){
                                            $("#deleteWorkspaceModal .modal-body").html("Please wait...");
                                            $("#deleteWorkspaceModal").modal("show");
                                    }'

                                ),
                            ),
                        )
                    )
                ),
                array(
                    'header' => 'View',
                    'class' => 'CButtonColumn',
                    'template' => '{options}',
                    'buttons' => array(
                        'options' => array(
                            'label' => '<span class="glyphicon glyphicon-list-alt"></span>',
                            'url' => 'Yii::app()->createUrl("project/view",array("id"=>$data->id))',
                            'options' => array(
                                'class' => 'action-link',
                            ),
                        )
                    )
                ),
                /*
                array(
                    'header' => 'Go to Task Manager',
                    'class' => 'CButtonColumn',
                    'template' => '{options}',
                    'buttons' => array(
                        'options' => array(
                            'label' => 'Go to Task Manager',

                            'url' => 'Yii::app()->createUrl("task/index",array("project_id"=>$data->id))',
                            'options' => array(
                                'class' => 'btn btn-danger',
                                'id'=>'link-'.uniqid(),
                            ),
                        )
                    )
                ),
                */
            ),
        )); ?>

    </div>
</div>
<br/>

protected/views/project/update.php
<?php
/* @var $this ProjectController */
/* @var $projectModel Project */

$this->widget('application.components.Ajaxmodal', array(
    'name' => 'deleteUserModal',
    'title' => 'Deleting User From WorkSpace',
    'width' => '80',
));
?>
<h3>Update data for workspace: <?php echo CHtml::encode($projectModel->name)?></h3>
<hr/>
<?php echo CHtml::link("<span class='glyphicon glyphicon-backward'></span> Back to Workspace Management",array('project/index'),array(
    'class'=>'action-link',
))?>
<br/>
<br/>
<?php $this->renderPartial('_form', array('projectModel'=>$projectModel,'ref'=>$ref,'userDataProvider'=>$userDataProvider,)); ?>