protected/controllers/SiteController.php
<?php

class SiteController extends Controller
{
	/**
	 * Declares class-based actions.
	 */

    public function filters(){
        array(
            'checkAccess',
        );
    }
	public function actions()
	{
		return array(
			// captcha action renders the CAPTCHA image displayed on the contact page
			'captcha'=>array(
				'class'=>'CCaptchaAction',
				'backColor'=>0xFFFFFF,
			),
			// page action renders "static" pages stored under 'protected/views/site/pages'
			// They can be accessed via: index.php?r=site/page&view=FileName
			'page'=>array(
				'class'=>'CViewAction',
			),
		);
	}

	/**
	 * This is the default 'index' action that is invoked
	 * when an action is not explicitly requested by users.
	 */

    public function actionIndex()
	{
        // The first time code to create the new user entity
        /*$user = new User;
        $user->first_name = "Zaher";
        $user->last_name = "Saad";
        $user->username = 'zaher';
        $user->login_name = 'zaher';
        $user->role = User::ROLE_ADMIN;
        $user->password = '1';
        $user->email = 'borhan@gmail.com';
        $user->password_repeat = '1';
        $user->save();
        Yii::app()->authManager->assign('administrator', $user->id);
        Yii::app()->authManager->assign('reassign', $user->id);
        Yii::app()->authManager->assign('view_archive', $user->id);
        Yii::app()->authManager->assign('end_task', $user->id);
        Yii::app()->user->logout();
        */
        if(Yii::app()->user->isGuest){
            $this->redirect(array('site/login'));
        }else{
            $user = User::model()->findByPk(Yii::app()->user->id);
            $this->redirect(array('task/index'));
        }
    }

	/**
	 * This is the action to handle external exceptions.
	 */
	public function actionError()
	{
		if($error=Yii::app()->errorHandler->error)
		{
			if(Yii::app()->request->isAjaxRequest)
				echo $error['message'];
			else
				$this->render('error', $error);
		}else{
            $this->redirect('site/index');
        }
	}

	/**
	 * Displays the login page
	 */

	public function actionLogin()
	{
        Yii::app()->user->logout();
        $this->pageTitle = "User Login";
        $loginModel=new LoginForm;
		// if it is ajax validation request
		if(isset($_POST['ajax']) && $_POST['ajax']==='login-form')
		{
			echo CActiveForm::validate($loginModel);
			Yii::app()->end();
		}
		// collect user input data
		if(isset($_POST['LoginForm']))
		{

            $loginModel->attributes=$_POST['LoginForm'];
			// validate user input and redirect to the previous page if valid
			if($loginModel->validate() && $loginModel->login()){
                $user = User::model()->findByPk(Yii::app()->user->id);
                $user->setStatus(User::STATE_ONLINE);
                $this->redirect(array('site/index'));
            }
		}
		// display the login form
		$this->render('login',array('loginModel'=>$loginModel));
	}

	/**
	 * Logs out the current user and redirect to homepage.
	 */

	public function actionLogout()
	{
        if(Yii::app()->user->isGuest){
            $this->redirect(array('site/login'));
        }else{
            $user = User::model()->findByPk(Yii::app()->user->id);
            $user->setStatus(User::STATE_OFFLINE);
            Yii::app()->user->logout();
            $this->redirect(array('site/login'));
        }

	}

}

protected/controllers/UserController.php
<?php

class UserController extends Controller
{
    /**
     * @var string the default layout for the views. Defaults to '//layouts/column2', meaning
     * using two-column layout. See 'protected/views/layouts/column2.php'.
     */
    public $layout = '//layouts/column2';

    /**
     * @return array action filters
     */
    public function filters()
    {
        return array(
            'checkAccess',
            'adminAccess - memberPasswordReset',
        );
    }

    /**
     * Specifies the access control rules.
     * This method is used by the 'accessControl' filter.
     * @return array access control rules
     */
    public function accessRules()
    {
        return array(
            array('allow', // allow all users to perform 'index' and 'view' actions
                'actions' => array('index', 'view'),
                'users' => array('*'),
            ),
            array('allow', // allow authenticated user to perform 'create' and 'update' actions
                'actions' => array('create', 'update'),
                'users' => array('@'),
            ),
            array('allow', // allow admin user to perform 'admin' and 'delete' actions
                'actions' => array('admin', 'delete'),
                'users' => array('admin'),
            ),
            array('deny', // deny all users
                'users' => array('*'),
            ),
        );
    }

    /**
     * Displays a particular model.
     * @param integer $id the ID of the model to be displayed
     */
    public function actionView($id)
    {
        $this->render('view', array(
            'model' => $this->loadModel($id),
        ));
    }

    /**
     * Creates a new model.
     * If creation is successful, the browser will be redirected to the 'index' page.
     */

    public function actionCreate()
    {
        $model = new User('create');
        $model->role = User::ROLE_MEMBER;
        // Uncomment the following line if AJAX validation is needed
        // $this->performAjaxValidation($model);

        if (isset($_POST['User'])) {

            $model->attributes = $_POST['User'];
            $model->status = User::STATE_OFFLINE;
            if ($model->validate()) {
                $model->first_name = strtolower($model->first_name);
                $model->last_name = strtolower($model->last_name);

                $model->save(false);
                switch ($model->role) {
                    case User::ROLE_ADMIN:
                        Yii::app()->authManager->assign('administrator', $model->id);
                        break;
                    case User::ROLE_PROJECT_SUPERVISOR:
                        Yii::app()->authManager->assign('project_supervisor', $model->id);
                        break;
                    case User::ROLE_MEMBER:
                        Yii::app()->authManager->assign('member', $model->id);
                        break;
                }

                if($model->viewArchivePermission){
                    Yii::app()->authManager->assign('view_archive', $model->id);
                }
                if($model->endTaskPermission){
                    Yii::app()->authManager->assign('end_task', $model->id);
                }
                if($model->reassignPermission){
                    Yii::app()->authManager->assign('reassign', $model->id);
                }
                if($model->viewReportPermission){
                    Yii::app()->authManager->assign('view_report', $model->id);
                }
                if($model->manageAutoTaskPermission){
                    Yii::app()->authManager->assign('manage_auto_tasks', $model->id);
                }

                $this->redirect(array('index'));
            }
        }
        if ($model->hasErrors()) {
            $model->password_repeat = "";
            $model->password = "";
        }
        $this->render('create', array(
            'model' => $model,
        ));
    }

    /**
     * Updates a particular model.
     * If update is successful, the browser will be redirected to the 'index' page.
     * @param integer $id the ID of the model to be updated
     */

    public function actionUpdate($id)
    {
        $model = $this->loadModel($id);
        // Uncomment the following line if AJAX validation is needed
        // $this->performAjaxValidation($model);
        $model->setScenario('update');
        if (isset($_POST['User'])) {
            $model->attributes = $_POST['User'];
            if ($model->validate()) {
                $model->first_name = strtolower($model->first_name);
                $model->last_name = strtolower($model->last_name);
                $model->save(false);
                $model->clearAssignment();
                $model->clearPermissions();
                switch ($model->role) {
                    case User::ROLE_ADMIN:
                        Yii::app()->authManager->assign('administrator', $model->id);
                        break;
                    case User::ROLE_PROJECT_SUPERVISOR:
                        Yii::app()->authManager->assign('project_supervisor', $model->id);
                        break;
                    case User::ROLE_MEMBER:
                        Yii::app()->authManager->assign('member', $model->id);
                        break;
                }
                if($model->viewArchivePermission){
                    Yii::app()->authManager->assign('view_archive', $model->id);
                }
                if($model->endTaskPermission){
                    Yii::app()->authManager->assign('end_task', $model->id);
                }
                if($model->reassignPermission){
                    Yii::app()->authManager->assign('reassign', $model->id);
                }
                if($model->viewReportPermission){
                    Yii::app()->authManager->assign('view_report', $model->id);
                }
                if($model->manageAutoTaskPermission){
                    Yii::app()->authManager->assign('manage_auto_tasks', $model->id);
                }
                $this->redirect(array('index'));
            }
        } else {
            $model->role = User::model()->getRole($model->id);
            $model->reassignPermission = $model->hasReassignPermission($model->id);
            $model->endTaskPermission = $model->hasEndTaskPermission($model->id);
            $model->viewArchivePermission = $model->hasViewArchivePermission($model->id);
            $model->viewReportPermission = $model->hasViewReportPermission($model->id);
            $model->manageAutoTaskPermission = $model->hasManageAutoTaskPermission($model->id);
        }

        $this->render('update', array(
            'model' => $model,
        ));
    }

    /**
     * @param integer $id the ID of the User of type (member,supervisor) you want to change his password
     */
    public function actionMemberPasswordReset($id){
        $userModel = $this->loadModel(intval($id));
        $userModel->setScenario('member_password_reset');
        $userModel->role = $userModel->getRole($userModel->id);
        if (isset($_POST['User'])) {
            $userModel->oldPassword = $_POST['User']['oldPassword'];
            if($userModel->password != $userModel->hashPassword($userModel->oldPassword)){
                $userModel->addError('oldPassword','Old Password is not correct');
            }
            $userModel->password = $_POST['User']['password'];
            $userModel->password_repeat = $_POST['User']['password_repeat'];

            if(!$userModel->hasErrors('oldPassword')){
                if ($userModel->validate()) {
                    $userModel->password = $userModel->hashPassword($userModel->password);
                    if($userModel->save(false)){
                        if($userModel->role==User::ROLE_ADMIN){
                            $this->redirect(array('index'));
                        }else{
                            $this->redirect(array('task/index'));
                        }
                    }
                }
            }

        }
        $userModel->password_repeat = "";
        $userModel->password = "";
        $this->render('member-password-reset',array(
            'model'=>$userModel,
        ));
    }

    /**
     * @param integer $id the ID of the User of type (administrator) you want to change his password
     */
    public function actionPasswordReset($id)
    {
        $userModel = $this->loadModel(intval($id));
        $userModel->setScenario('password_reset');
        if (isset($_POST['User'])) {
            $userModel->password = $_POST['User']['password'];
            $userModel->password_repeat = $_POST['User']['password_repeat'];
            if ($userModel->validate()) {
                $userModel->password = $userModel->password = $userModel->hashPassword($userModel->password);
                if($userModel->save(false)){
                    $this->redirect(array('index'));
                }
            }
        }
        $userModel->password_repeat = "";
        $userModel->password = "";

        $this->render('password_reset', array(
            'model' => $userModel,
        ));
    }

    public function actionChangeStatus(){
        if(isset($_POST['status_code'])){
            $statusCode = intval($_POST['status_code']);
            $user = $this->loadModel(Yii::app()->user->id);
            $p_status_code = $user->status;
            if($user->setStatus($statusCode)){
                echo CJSON::encode(array(
                    'status'=>true,
                    'p_status_code'=>$p_status_code,
                    'status_code'=>$statusCode,
                ));
            }else{
                echo CJSON::encode(array(
                    'status'=>false,
                    'p_status_code'=>$p_status_code,
                ));
            }
        }else{
            throw new CHttpException(400);
        }
    }

    public function actionDelete($id)
    {

protected/views/user/create.php
<?php
/* @var $this UserController */
/* @var $model User */

$this->breadcrumbs=array(
	'Users'=>array('index'),
	'Create',
);

$this->menu=array(
	array('label'=>'List User', 'url'=>array('index')),
	array('label'=>'Manage User', 'url'=>array('admin')),
);
?>

<h3>Create A New User - <small>fields with * are required</small></h3>
<hr/>

<?php echo CHtml::link("<span class='glyphicon glyphicon-backward'></span> Back to User Management",array('user/index'),array(
    'class'=>'action-link',
))?>
    <br/>
    <br/>
<?php $this->renderPartial('_form', array('model'=>$model)); ?>

protected/views/user/edit-user-followup-list.php
<?php
/**
 *
 * Created by PhpStorm.
 * User: Dell 3521
 * Date: 09/01/15
 * Time: 05:59 م
 */

Yii::app()->clientScript->registerScript("edit-follow-up-list",'
$(function(){
    $(".Tabled table").addClass("table");
    $(".Tabled table").addClass("table-condensed");
    $(".group-summery-container").html($(".group-grid-summery").html());
    $(".group-grid-summery").hide();
    $(".user-summery-container").html($(".user-grid-summery").html());
    $(".user-grid-summery").hide();
    $(".readonly-c input").attr("readonly",true);
    updateDeleteLink();

});
var updateDeleteLink = function(){
    $(".delete-user-link").click(function(event){
        var userId = $(this).parent().parent().parent("li").attr("user-id");
        var supervisorId = $(this).parent().parent().parent("li").attr("supervisor-id");
        $.ajax({
            "url":"'.$this->createUrl('user/removeFromFollowList').'",
            "type":"POST",
            "dataType":"json",
            "data":{
                "uId":userId,
                "sId":supervisorId
            },
            "success":function(data){
                if(data.status){
                    $("#user-grid").yiiGridView("update");
                    updateFollowingList(supervisorId);
                }
                $(this).attr("disabled",false);
            },
            "beforeSend":function(){
                $(this).attr("disabled",true);
                $("#loading-indicator").show();
            },
            "error":function(){
                $("#loading-indicator").hide();
            }
        });
    });
}

var updateFollowingList = function(supervisorId){
    $.ajax({
        "url":"'.$this->createUrl('user/getFollowingUserList').'",
        "data":{
            "id":supervisorId
        },
        "type":"GET",
        "success":function(data){
            $("#followup-list-container").html(data);
            $("#loading-indicator").hide();
        }
    });
}
',CClientScript::POS_END);

?>
<div class="row">
    <div class="col-md-9">
        <div class="row">
            <div class="col-md-12">
                <h4>Edit FollowUp List for user: <?php echo $supervisor->username;?></h4>
                <hr/>

                <?php echo CHtml::link("<span class='glyphicon glyphicon-backward'></span> Back to User Management",array('user/index'),array(
                    'class'=>'action-link',
                ))?>
                <br/>
                <br/>
            </div>
        </div>
        <?php echo CHtml::beginForm($this->createUrl('user/updateFList'),'POST')?>
        <div class="row">
            <?php echo CHtml::hiddenField('supervisor_id',$supervisor->id)?>
            <div class="col-md-6" id="group-list-container">
                <?php
                    $this->renderPartial('partials/_group-list',array(
                        'groupsDataProvider'=>$groupsDataProvider,
                    ));
                ?>
                <div class="group-summery-container"></div>
            </div>
            <div class="col-md-6" id="user-list-container">
                <?php
                    $this->renderPartial('partials/_user-list',array(
                        'groupsDataProvider'=>$usersDataProvider,
                ));
                ?>
                <div class="user-summery-container"></div>
            </div>
        </div>
        <div class="clearfix"></div>
        <div class="row">
            <div class="col-md-4">
                <?php echo CHtml::ajaxSubmitButton("Update FollowUp List",Yii::app()->createUrl("user/updateFList"),array(
                    'dataType'=>'json',
                    'success'=>'js:function(data){
                        $("#update-follow-up-submit-button").attr("disabled",false);
                        if(data.status){
                            updateFollowingList(data.sId);
                            $("#user-grid").yiiGridView("update");
                        }
                    }',
                    'beforeSend'=>'js:function(){
                        $("#update-follow-up-submit-button").attr("disabled",true);
                        $("#loading-indicator").show();
                    }'
                ),array(
                    'class'=>'btn btn-success',
                    'id'=>'update-follow-up-submit-button',
                ));?>
            </div>
        </div>
    </div>
    <?php echo CHtml::endForm()?>
    <div id="followup-list-container" class="col-md-3">
        <?php
            $this->renderPartial('partials/_follow-up-list',array(
                'followUpUsers'=>$followUpUsers,
                'supervisorId'=>$supervisorId,
                'supervisor'=>$supervisor,
            ));
        ?>
    </div>
</div>

protected/views/user/index.php
<?php
/* @var $this UserController */
/* @var $dataProvider CActiveDataProvider */

Yii::app()->clientScript->registerScript('user-grid', "
$(function(){
        $('.Tabled table').addClass('table');
});
",CClientScript::POS_END);

$this->widget('application.components.Ajaxmodal', array(
    'name' => 'assignToProjectModal',
    'title' => 'Assign to a Project',
    'width' => '600px',
));
$this->widget('application.components.Ajaxmodal', array(
    'name' => 'setCurrentProjectModal',
    'title' => 'Set Current Project',
    'width' => '600px',
));

$this->widget('application.components.Ajaxmodal', array(
    'name' => 'deleteUserModal',
    'title' => 'Deleting User',
    'width' => '600px',
));

$this->widget('application.components.Ajaxmodal', array(
    'name' => 'statusModal',
    'title' => 'Status',
    'width' => '600px',
));

$this->widget('application.components.Ajaxmodal', array(
    'name' => 'showUserInfoModal',
    'title' => 'Status',
    'width' => '600px',
));
?>
<?php echo CHtml::link('Create User',$this->createUrl('user/create'),array(
    'class'=>'btn btn-success btn-sm',
))?>

<hr/>



<div class="row">
    <div class="col-md-12">
        <br/>
        <?php $this->widget('zii.widgets.grid.CGridView', array(
            'id' => 'user-grid',
            'summaryText' => '<span>Total No Of Users: {count}</span><br/>',
            'afterAjaxUpdate' => 'js:function(){
        	$(".Tabled table").addClass("table");
            }',
            'htmlOptions' => array(
                'class' => 'Tabled',
            ),
            'cssFile' => Yii::app()->baseUrl . '/css/main.css',
            'dataProvider' => $dataProvider,
            'columns' => array(
                'first_name',
                'last_name',
                array(
                    'header'=>'User Name',
                    'name'=>'username',
                    'cssClassExpression'=>'',
                ),
                array(
                    'header'=>'Status',
                    'value'=>'CommonFunctions::getLabel($data->status,CommonFunctions::USER_STATUS)',
                    'type'=>'raw',
                ),
                array(
                    'header' => 'Edit',
                    'class' => 'CButtonColumn',
                    'template' => '{options}',
                    'buttons' => array(
                        'options' => array(
                            'label' => '<span class="glyphicon glyphicon-pencil"></span>',
                            'url' => 'Yii::app()->createUrl("user/update",array("id"=>$data->id))',
                            'options' => array(
                                'class' => 'action-link',
                            ),
                        )
                    )
                ),
                array(
                    'type'=>'raw',
                    'header'=>'Role',
                    'value'=>'$data->getRoleText()',
                ),
                array(
                    'header'=>'Follow Up count',
                    'value'=>'count($data->followUpUsers)',
                    'visible'=>'$data->isSupervisor($data->id)',
                ),
                array(
                    'header' => 'Manager Follow Up List',
                    'class' => 'CButtonColumn',
                    'template' => '{options}',
                    'buttons' => array(
                        'options' => array(
                            'label' => '<span class="glyphicon glyphicon-pencil"></span>',
                            'url' => 'Yii::app()->createUrl("user/editFollowUpList",array("id"=>$data->id))',
                            'visible'=>'$data->isSupervisor($data->id)',
                            'options' => array(
                                'class' => 'action-link',
                            ),
                        ),

                    )
                ),
                array(
                    'header' => 'Reset Password',
                    'class' => 'CButtonColumn',
                    'template' => '{options}',
                    'buttons' => array(
                        'options' => array(
                            'label' => '<span class="glyphicon glyphicon-lock"></span>',
                            'url' => 'Yii::app()->createUrl("user/passwordReset",array("id"=>$data->id))',
                            'options' => array(
                                'class' => 'action-link',
                            ),
                        )
                    )
                ),
                array(
                    'header' => 'Delete User',
                    'class' => 'CButtonColumn',
                    'template' => '{options}',
                    'buttons' => array(
                        'options' => array(
                            'label' => '<span class="glyphicon glyphicon-trash"></span>',
                            'url' => 'Yii::app()->createUrl("user/delete",array("id"=>$data->id))',
                            'options' => array(
                                'class' => 'action-link',
                                'confirm'=>'Are you sure you want to delete this user?',
                                'ajax' => array(
                                    'url' => 'js:$(this).attr("href")',
                                    'type' => 'GET',
                                    'dataType'=>'json',
                                    'success' => 'js:function(data){
                                            $("#deleteUserModal .modal-body").html(data.message);
                                            if(data.status){
                                                $("#user-grid").yiiGridView("update");
                                            }else{
                                            }
                                    }',

                                    'beforeSend' => 'js:function(){
                                            $("#deleteUserModal .modal-body").html("Please wait...");
                                            $("#deleteUserModal").modal("show");
                                    }'

                                ),
                            ),
                        )
                    )
                ),
                array(
                    'header' => 'Get User Info',
                    'class' => 'CButtonColumn',
                    'template' => '{options}',
                    'buttons' => array(
                        'options' => array(
                            'label' => '<span class="glyphicon glyphicon-user"></span>',
                            'url' => 'Yii::app()->createUrl("user/view",array("id"=>$data->id))',
                            'options' => array(
                                'class' => 'action-link',
                                /*'ajax' => array(
                                    'url' => 'js:$(this).attr("href")',
                                    'type' => 'GET',
                                    'success' => 'js:function(data){
                                            $("#showUserInfoModal .modal-body").html(data);
                                        }',
                                    'beforeSend' => 'js:function(){
                                            $("#showUserInfoModal .modal-body").html("Please wait...");
                                            $("#showUserInfoModal").modal("show");
                                        }'

                                ),*/
                            ),
                        )
                    )
                ),

                /*array(
                    'header' => 'Assign to Project',
                    'class' => 'CButtonColumn',
                    'template' => '{options}',
                    'buttons' => array(
                        'options' => array(
                            'label' => 'Assign to Project',
                            'click' => 'js:function(event){
                        var ajaxUrl = $(this).attr("href");
                        $.ajax({
                          "url":ajaxUrl,
                          "type":"GET",
                          "success":function(data){
                            $("#assignToProjectModal .modal-body").html(data);
                          },
                          "beforeSend":function(){
                            $("#assignToProjectModal .modal-body").html("Please Wait...");
                            $("#assignToProjectModal").modal("show");
                          }
                        });
                        return false;
                    }',
                            'url' => 'Yii::app()->createUrl("user/getAssignToProjectForm",array("uId"=>$data->id))',
                            'options' => array(
                                'class' => 'btn btn-danger',
                                'id'=>'link-'.uniqid(),
                            ),
                        )
                    )
                ),*/
            ),
        )); ?>

    </div>
</div>
<br/>

protected/views/user/password_reset.php
<?php
/* @var $this UserController */
/* @var $model User */
/* @var $form CActiveForm */

Yii::app()->clientScript->registerScript("course_script", '
$(function(){
    $(".ok-sign").hide();
    $(".error-sign").hide();
});
', CClientScript::POS_END);

?>
<h3>Update password for user: <?php echo $model->first_name . " " . $model->last_name; ?>  -
    <small>fields with * are required</small>
</h3>
<hr/>
<?php echo CHtml::link("<span class='glyphicon glyphicon-backward'></span> Back to User Management",array('user/index'),array(
    'class'=>'action-link',
))?>
<br/>
<br/>
<div class="form">
    <?php $form = $this->beginWidget('CActiveForm', array(
        'id' => 'task-form',
        // Please note: When you enable ajax validation, make sure the corresponding
        // controller action is handling ajax validation correctly.
        // There is a call to performAjaxValidation() commented in generated controller code.
        // See class documentation of CActiveForm for details on this.
        'enableAjaxValidation' => false,
        'enableClientValidation' => false,
        'focus' => array($model, 'password'),
        'clientOptions' => array(
            'successCssClass' => 'has-success',
            'errorCssClass' => 'has-error',
            'validatingErrorMessage' => '',
            'inputContainer' => '.form-group',
            'afterValidateAttribute' => 'js:function(form, attribute, data, hasError){
                $("#"+attribute.inputID).siblings(".error-sign").hide();
                $("#"+attribute.inputID).siblings(".ok-sign").hide();
                if(hasError){
                    $("#"+attribute.inputID).siblings(".error-sign").show();
                }else {
                    $("#"+attribute.inputID).siblings(".ok-sign").show();
                }
            }',
        ),
        'htmlOptions' => array(
            'role' => 'form',
            'class' => 'form-horizontal',
        ),
    )); ?>
    <div class="row">
        <div class="col-md-offset-3 col-md-6">
            <div class="form-group has-feedback">
                <?php echo $form->hiddenField($model,'id');?>
                <?php echo $form->labelEx($model, 'password', array('class' => 'col-md-4 control-label')); ?>
                <div class="col-md-8 input-container">
                    <?php echo $form->passwordField($model, 'password', array('size' => 60, 'maxlength' => 255, 'class' => 'form-control')); ?>
                    <span class="glyphicon glyphicon-remove form-control-feedback error-sign"></span>
                    <span class="glyphicon glyphicon-ok form-control-feedback ok-sign"></span>
                    <?php echo $form->error($model, 'password'); ?>
                </div>
            </div>
            <div class="form-group has-feedback">
                <?php echo $form->labelEx($model, 'password_repeat', array('class' => 'col-md-4 control-label')); ?>
                <div class="col-md-8 input-container">
                    <?php echo $form->passwordField($model, 'password_repeat', array('placeholder'=>'Repeat to validate Password','size' => 60, 'maxlength' => 255, 'class' => 'form-control')); ?>
                    <span class="glyphicon glyphicon-remove form-control-feedback error-sign"></span>
                    <span class="glyphicon glyphicon-ok form-control-feedback ok-sign"></span>
                    <?php echo $form->error($model, 'password_repeat'); ?>
                </div>
            </div>
            <div class="form-group">
                <div class="col-md-offset-4 col-md-8">
                    <?php echo CHtml::submitButton("Reset Password" ,array(
                        'class'=>'btn btn-danger',
                    ))?>
                </div>
            </div>
        </div>

        <div class="clearfix"></div>
    </div>

    <?php $this->endWidget(); ?>
</div><!-- form -->